language: php

notifications:
  email: false

php:
  - "7.3"
  - "7.4"
  - "8.0"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

install:
    - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit tests
